# Generated by Django 3.0.7 on 2020-07-19 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200717_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='comment',
            name='auth_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='usename',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
