# Generated by Django 3.0.7 on 2020-07-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200719_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='usename',
            new_name='username',
        ),
    ]
