# Generated by Django 3.0.3 on 2020-09-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_bookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='image',
        ),
    ]
